use msadbarchive;
delete from address;
delete from adjustment_log;
delete from attendance;
delete from dependents;
delete from dutydetails;
delete from guards;
delete from holiday;
delete from incidentreport;
delete from payroll;
delete from period;
delete from personsinvolved;
delete from request;
delete from request_assign;
delete from request_unassign;
delete from sduty_assignment;
use msadb;