insert into address (gid, atype, Country, City, Streetno, brgy, street) values (1, 1, 'Uzbekistan', 'Chimboy Shahri', '6', null, 'Upham');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (2, 1, 'Indonesia', 'Cigagade', '08497', null, 'Lillian');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (3, 1, 'Croatia', 'Sukošan', '133', null, '5th');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (4, 1, 'Philippines', 'Santa Cruz', '64', null, 'Harper');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (5, 1, 'Liechtenstein', 'Schaan', '4529', null, 'Fremont');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (6, 1, 'Japan', 'Kaminokawa', '70', null, 'Ridgeview');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (7, 1, 'China', 'Shanghudi', '3782', null, 'Lake View');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (8, 1, 'Italy', 'Milano', '81365', 'Lombardia', 'Sundown');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (9, 1, 'Chile', 'Vallenar', '820', null, 'Sloan');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (10, 1, 'Brazil', 'Florestópolis', '3535', null, 'West');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (11, 1, 'Dominican Republic', 'Partido', '2941', null, 'Kipling');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (12, 1, 'France', 'Paris 18', '3', 'Île-de-France', 'Ruskin');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (13, 1, 'Indonesia', 'Panite', '0633', null, 'Welch');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (14, 1, 'Thailand', 'Tha Yang', '3', null, 'Longview');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (15, 1, 'Indonesia', 'Beo', '762', null, 'Thierer');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (16, 1, 'Albania', 'Otllak', '3075', null, 'Susan');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (17, 1, 'Egypt', 'Al Fayyūm', '4108', null, 'Reinke');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (18, 1, 'Portugal', 'Chã', '336', 'Santarém', 'Meadow Ridge');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (19, 1, 'Indonesia', 'Hauhena', '3', null, 'Melrose');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (20, 1, 'Peru', 'Paccho', '5087', null, 'Barnett');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (21, 1, 'Indonesia', 'Kekeri', '5', null, 'Ludington');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (22, 1, 'Kosovo', 'Dragash', '38', null, 'Mandrake');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (23, 1, 'China', 'Yingwusitang', '846', null, 'Mayfield');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (24, 1, 'China', 'Yangdian', '8001', null, 'Dottie');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (25, 1, 'China', 'Awat', '48999', null, 'Rutledge');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (26, 1, 'Indonesia', 'Sigli', '53', null, 'Eliot');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (27, 1, 'Belarus', 'Khodasy', '71', null, 'Elmside');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (28, 1, 'Indonesia', 'Kadubera', '53972', null, 'Straubel');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (29, 1, 'Russia', 'Sivaki', '84688', null, 'Annamark');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (30, 1, 'Poland', 'Pomiechówek', '34', null, 'Thompson');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (31, 1, 'Poland', 'Sokółka', '1', null, 'Esch');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (32, 1, 'Cameroon', 'Garoua Boulaï', '54', null, 'La Follette');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (33, 1, 'United States', 'Pittsburgh', '8', 'Pennsylvania', 'Oak');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (34, 1, 'Venezuela', 'Tía Juana', '1', null, 'New Castle');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (35, 1, 'Indonesia', 'Rato', '56', null, 'Gerald');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (36, 1, 'Indonesia', 'Banjar Jagasatru', '1953', null, 'Little Fleur');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (37, 1, 'Armenia', 'Aygavan', '93', null, 'Springview');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (38, 1, 'Morocco', 'Sidi Yahia el Gharb', '397', null, 'Marquette');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (39, 1, 'Russia', 'Krasnaya Polyana', '1070', null, 'Mallory');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (40, 1, 'Portugal', 'São Paio de Seide', '831', 'Braga', 'Shasta');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (41, 1, 'Indonesia', 'Bajomulyo', '75355', null, 'Kipling');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (42, 1, 'Ireland', 'Thomastown', '6', null, 'Anthes');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (43, 1, 'Sweden', 'Huskvarna', '6', 'Jönköping', 'Riverside');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (44, 1, 'Poland', 'Brzączowice', '4831', null, 'Shopko');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (45, 1, 'Estonia', 'Võhma', '76', null, 'Manufacturers');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (46, 1, 'Greece', 'Anaráchi', '7891', null, 'Chive');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (47, 1, 'Panama', 'Cartí Suitupo', '53552', null, 'Declaration');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (48, 1, 'South Africa', 'Williston', '5356', null, 'Spenser');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (49, 1, 'Belarus', 'Vidzy', '8', null, 'Corben');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (50, 1, 'Philippines', 'Corcuera', '869', null, 'Nancy');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (51, 1, 'Cuba', 'Ciro Redondo', '2', null, 'Algoma');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (52, 1, 'Philippines', 'Maria Cristina', '0722', null, 'Valley Edge');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (53, 1, 'United States', 'Springfield', '35', 'Illinois', 'Delladonna');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (54, 1, 'China', 'Qiuchuan', '5', null, 'Commercial');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (55, 1, 'Comoros', 'Madjeouéni', '4', null, 'Truax');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (56, 1, 'China', 'Daba', '88726', null, 'Farragut');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (57, 1, 'Egypt', 'Kousa', '603', null, 'Golf Course');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (58, 1, 'Czech Republic', 'Kraslice', '59', null, 'La Follette');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (59, 1, 'Egypt', 'Marsa Alam', '12', null, 'Moland');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (60, 1, 'Dominican Republic', 'Ensanche Luperón', '6042', null, 'Lunder');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (61, 1, 'Germany', 'Hamburg', '2268', 'Hamburg', 'Annamark');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (62, 1, 'Vietnam', 'An Châu', '8400', null, 'Nevada');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (63, 1, 'Russia', 'Khokhryaki', '6067', null, 'Clemons');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (64, 1, 'Philippines', 'Baylo', '930', null, 'Granby');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (65, 1, 'Indonesia', 'Wahang Dua', '1490', null, 'Shasta');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (66, 1, 'Indonesia', 'Babakankadu', '1', null, 'Lunder');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (67, 1, 'Afghanistan', 'Uruzgān', '054', null, 'Pearson');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (68, 1, 'Sweden', 'Västra Frölunda', '9', 'Västra Götaland', 'Esker');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (69, 1, 'Iran', 'Dalgān', '98703', null, 'Dixon');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (70, 1, 'Ireland', 'Longford', '56', null, 'Spenser');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (71, 1, 'Greece', 'Vári', '946', null, 'Bluestem');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (72, 1, 'Japan', 'Toba', '2037', null, 'Delladonna');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (73, 1, 'China', 'Weizhou', '0', null, 'Oriole');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (74, 1, 'Indonesia', 'Klagen', '12514', null, 'Village Green');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (75, 1, 'Norway', 'Frei', '7878', 'More og Romdal', 'Elmside');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (76, 1, 'Russia', 'Satinka', '91', null, 'Londonderry');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (77, 1, 'China', 'Xiaqiao', '02', null, 'Bluejay');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (78, 1, 'Kosovo', 'Lipljan', '21562', null, 'Amoth');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (79, 1, 'China', 'Hufang', '2', null, 'Brentwood');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (80, 1, 'Indonesia', 'Krajan Nglinggis', '71389', null, 'Holmberg');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (81, 1, 'Russia', 'Yefremov', '506', null, 'Kim');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (82, 1, 'Portugal', 'Fraga', '59869', 'Porto', 'Rowland');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (83, 1, 'China', 'Baitu', '031', null, 'Briar Crest');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (84, 1, 'Poland', 'Skórzec', '26421', null, 'Porter');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (85, 1, 'China', 'Qingnianlu', '393', null, 'Anthes');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (86, 1, 'China', 'Dongpu', '17', null, 'Eagle Crest');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (87, 1, 'Mauritania', 'Nouakchott', '92680', null, 'Bluejay');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (88, 1, 'Sweden', 'Linköping', '375', 'Östergötland', 'Orin');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (89, 1, 'Spain', 'Valladolid', '2', 'Castilla - Leon', 'Macpherson');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (90, 1, 'Thailand', 'Prang Ku', '571', null, 'Scofield');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (91, 1, 'China', 'Liqi', '42', null, 'Sugar');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (92, 1, 'Philippines', 'Doyong', '31', null, 'Scofield');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (93, 1, 'Portugal', 'Portalegre', '5', 'Portalegre', 'Fieldstone');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (94, 1, 'China', 'Donghai', '5365', null, 'Luster');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (95, 1, 'Sweden', 'Uddevalla', '902', 'Västra Götaland', 'Tennessee');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (96, 1, 'Canada', 'Carbonear', '2563', 'Newfoundland and Labrador', 'Jay');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (97, 1, 'Mongolia', 'Buyant', '94', null, 'Graedel');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (98, 1, 'Russia', 'Kultayevo', '66', null, '1st');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (99, 1, 'Russia', 'Podsineye', '9107', null, 'Sundown');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (100, 1, 'Kenya', 'Homa Bay', '89216', null, 'Barby');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (101, 1, 'Canada', 'Smiths Falls', '070', 'Ontario', 'Banding');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (102, 1, 'Indonesia', 'Tegalalang', '8977', null, 'Sage');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (103, 1, 'Peru', 'Pueblo Nuevo', '78', null, 'Swallow');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (104, 1, 'Poland', 'Brudzeń Duży', '5', null, 'Toban');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (105, 1, 'Indonesia', 'Cibinong', '8', null, 'Butterfield');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (106, 1, 'China', 'Xiaohe', '37895', null, 'Lukken');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (107, 1, 'China', 'Kuasha', '5635', null, 'Ridge Oak');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (108, 1, 'Indonesia', 'Bolorejo', '3', null, 'Cambridge');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (109, 1, 'China', 'Zhaike', '065', null, 'Blackbird');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (110, 1, 'Jordan', '‘Anjarah', '34', null, 'Meadow Ridge');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (111, 1, 'Luxembourg', 'Itzig', '4', null, 'Washington');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (112, 1, 'Russia', 'Vilya', '71', null, 'Ruskin');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (113, 1, 'Germany', 'Hannover', '0', 'Niedersachsen', 'Corben');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (114, 1, 'Russia', 'Zakamensk', '7937', null, 'Grayhawk');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (115, 1, 'Belarus', 'Krasnaye', '296', null, 'Fairfield');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (116, 1, 'Ukraine', 'Kapitanivka', '9', null, 'Barnett');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (117, 1, 'Morocco', 'Boulaouane', '632', null, 'Arrowood');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (118, 1, 'Malawi', 'Chipyela', '83', null, 'Cambridge');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (119, 1, 'China', 'Yunlong', '14237', null, 'Johnson');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (120, 1, 'Poland', 'Sędziszów', '3', null, 'Sage');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (121, 1, 'Russia', 'Novotroitskaya', '83518', null, 'Corscot');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (122, 1, 'Ukraine', 'Petrivka', '20242', null, 'Daystar');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (123, 1, 'China', 'Nancheng', '7634', null, 'Pierstorff');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (124, 1, 'Brazil', 'Bataiporã', '37614', null, 'Tennyson');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (125, 1, 'Indonesia', 'Widorokandang', '7306', null, 'Red Cloud');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (126, 1, 'Chile', 'Vallenar', '08651', null, 'Nancy');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (127, 1, 'Nigeria', 'Babana', '6', null, 'Crowley');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (128, 1, 'Indonesia', 'Selasari', '2760', null, 'Gateway');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (129, 1, 'Nigeria', 'Abua', '97889', null, 'Donald');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (130, 1, 'Ghana', 'Akim Swedru', '94', null, 'Center');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (131, 1, 'Indonesia', 'Duko', '78543', null, 'Park Meadow');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (132, 1, 'China', 'Jinshanwei', '92032', null, 'Elka');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (133, 1, 'Indonesia', 'Banjar Budakeling', '3', null, 'Bay');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (134, 1, 'Germany', 'Bielefeld', '6', 'Nordrhein-Westfalen', 'Pearson');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (135, 1, 'China', 'Tengqiao', '667', null, 'Reindahl');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (136, 1, 'China', 'Pengxing', '3841', null, 'Talisman');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (137, 1, 'Afghanistan', 'Herāt', '5393', null, 'Debra');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (138, 1, 'China', 'Wuning', '0170', null, 'Elka');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (139, 1, 'China', 'Yag La', '379', null, 'Quincy');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (140, 1, 'Indonesia', 'Cibebek', '42590', null, 'Sundown');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (141, 1, 'Poland', 'Maniowy', '647', null, 'Mallory');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (142, 1, 'South Africa', 'Vredefort', '907', null, 'Sugar');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (143, 1, 'Sri Lanka', 'Jaffna', '0', null, '1st');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (144, 1, 'Bosnia and Herzegovina', 'Vareš', '3932', null, 'Bashford');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (145, 1, 'Indonesia', 'Semambung', '7580', null, 'Heath');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (146, 1, 'China', 'Qingnianlu', '0013', null, 'Lotheville');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (147, 1, 'Ukraine', 'Koryukivka', '503', null, 'Main');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (148, 1, 'Solomon Islands', 'Honiara', '22879', null, 'Hoepker');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (149, 1, 'Sweden', 'Strömsund', '8324', 'Jämtland', 'Hovde');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (150, 1, 'Iran', 'Kīsh', '23', null, 'Logan');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (151, 1, 'Ukraine', 'Subottsi', '4', null, 'Autumn Leaf');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (152, 1, 'Albania', 'Udënisht', '0', null, 'Comanche');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (153, 1, 'Palestinian Territory', 'Maythalūn', '8', null, 'Center');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (154, 1, 'Colombia', 'Málaga', '518', null, 'Transport');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (155, 1, 'Zimbabwe', 'Bulawayo', '048', null, 'Forster');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (156, 1, 'China', 'Niushou', '2323', null, 'Tennessee');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (157, 1, 'Australia', 'Sydney', '3', 'New South Wales', 'Charing Cross');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (158, 1, 'Syria', 'Al Ḩaffah', '24397', null, 'Mccormick');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (159, 1, 'Russia', 'Aykhal', '90', null, 'Macpherson');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (160, 1, 'Czech Republic', 'Leština', '61714', null, 'Basil');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (161, 1, 'China', 'Heitan', '6', null, 'Victoria');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (162, 1, 'United States', 'Gatesville', '18', 'Texas', 'Forest Run');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (163, 1, 'China', 'Longnan', '1809', null, 'Fallview');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (164, 1, 'Thailand', 'Chum Phae', '3685', null, 'Rigney');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (165, 1, 'Indonesia', 'Juwana', '4662', null, 'Lien');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (166, 1, 'Bosnia and Herzegovina', 'Podbrdo', '3', null, 'Anhalt');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (167, 1, 'Brazil', 'Boa Esperança', '7', null, 'Rowland');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (168, 1, 'United States', 'Gainesville', '60049', 'Florida', 'Dahle');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (169, 1, 'Russia', 'Il’skiy', '88', null, 'North');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (170, 1, 'China', 'Xinrong', '3', null, 'Summerview');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (171, 1, 'Iceland', 'Hafnarfjörður', '76', null, 'Wayridge');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (172, 1, 'Malta', 'Gudja', '41', null, 'Westridge');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (173, 1, 'Russia', 'Sosnovaya Polyana', '41907', null, 'Mitchell');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (174, 1, 'China', 'Caozhen', '41', null, 'Huxley');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (175, 1, 'China', 'Dushi', '33', null, 'Michigan');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (176, 1, 'Colombia', 'La Jagua de Ibirico', '03756', null, 'Bluejay');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (177, 1, 'Venezuela', 'Las Mercedes', '94063', null, 'Waxwing');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (178, 1, 'Poland', 'Frydek', '2206', null, 'Corben');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (179, 1, 'China', 'Boyu', '540', null, 'International');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (180, 1, 'Slovenia', 'Slovenska Bistrica', '7301', null, 'Hudson');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (181, 1, 'United States', 'Milwaukee', '8277', 'Wisconsin', 'Hovde');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (182, 1, 'China', 'Bajingzi', '35890', null, 'Green Ridge');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (183, 1, 'Paraguay', 'Piribebuy', '494', null, 'Mockingbird');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (184, 1, 'Philippines', 'Doña Remedios Trinidad', '677', null, 'Troy');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (185, 1, 'Lithuania', 'Zarasai', '34', null, 'Lakewood');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (186, 1, 'Argentina', 'Famaillá', '1614', null, 'Green');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (187, 1, 'Russia', 'Leskolovo', '298', null, 'Katie');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (188, 1, 'China', 'Benhao', '777', null, 'Gina');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (189, 1, 'China', 'Pailiao', '5285', null, 'Nova');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (190, 1, 'Argentina', 'Berón de Astrada', '77', null, 'Service');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (191, 1, 'Nigeria', 'Igbor', '5206', null, 'Acker');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (192, 1, 'China', 'Tong’an', '413', null, 'Oneill');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (193, 1, 'Russia', 'Navashino', '7', null, 'Alpine');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (194, 1, 'China', 'Maqia', '92992', null, 'Merchant');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (195, 1, 'Philippines', 'Loyola', '65', null, 'Morningstar');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (196, 1, 'Japan', 'Gōdo', '17', null, 'Birchwood');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (197, 1, 'Russia', 'Novyy Oskol', '8813', null, 'Bartillon');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (198, 1, 'Sweden', 'Stockholm', '516', 'Stockholm', 'Lake View');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (199, 1, 'China', 'Zhongshan', '87', null, 'Lakewood');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (200, 1, 'Russia', 'Tunoshna', '993', null, 'Crest Line');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (201, 1, 'China', 'Tongmuluo', '5', null, 'Dakota');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (202, 1, 'Ukraine', 'Bezlyudivka', '38', null, 'Lerdahl');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (203, 1, 'Oman', 'Şaḩam', '54', null, 'John Wall');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (204, 1, 'China', 'Hexiangqiao', '90', null, 'Sutherland');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (205, 1, 'Greece', 'Goúvai', '7341', null, 'Farwell');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (206, 1, 'Canada', 'Macamic', '7573', 'Québec', 'Esch');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (207, 1, 'Albania', 'Miras', '8099', null, 'Toban');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (208, 1, 'Philippines', 'Manicahan', '335', null, 'Morningstar');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (209, 1, 'Comoros', 'Pajé', '941', null, 'Hovde');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (210, 1, 'Colombia', 'Envigado', '73', null, 'Muir');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (211, 1, 'Indonesia', 'Dodu Dua', '29', null, 'Debra');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (212, 1, 'China', 'Longtan', '9783', null, 'Killdeer');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (213, 1, 'Norway', 'Bodø', '46176', 'Nordland', 'Oakridge');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (214, 1, 'Russia', 'Bogorodsk', '6700', null, 'Fremont');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (215, 1, 'Azerbaijan', 'Hacıqabul', '4690', null, 'Schurz');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (216, 1, 'Russia', 'Bogandinskiy', '933', null, 'Merry');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (217, 1, 'Guatemala', 'Santa Clara La Laguna', '6947', null, 'Anniversary');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (218, 1, 'France', 'Vénissieux', '288', 'Rhône-Alpes', 'Debs');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (219, 1, 'China', 'Xialiao', '342', null, 'Elka');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (220, 1, 'Armenia', 'Sovetakan', '61677', null, 'Westridge');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (221, 1, 'Bosnia and Herzegovina', 'Hiseti', '5358', null, 'Lighthouse Bay');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (222, 1, 'China', 'Xincheng', '0', null, 'Towne');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (223, 1, 'Afghanistan', 'Ārt Khwājah', '54563', null, 'Westridge');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (224, 1, 'Indonesia', 'Gudang', '25561', null, 'Talmadge');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (225, 1, 'Indonesia', 'Karangturi', '1938', null, 'Meadow Vale');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (226, 1, 'United States', 'High Point', '4964', 'North Carolina', 'Truax');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (227, 1, 'Peru', 'Santa Catalina', '15102', null, 'Pepper Wood');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (228, 1, 'Israel', 'Kafr Miṣr', '5', null, 'Longview');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (229, 1, 'Comoros', 'Madjeouéni', '84194', null, 'Briar Crest');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (230, 1, 'Thailand', 'Thung Yang Daeng', '05946', null, 'Michigan');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (231, 1, 'Czech Republic', 'Nové Sedlo', '3934', null, 'Declaration');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (232, 1, 'Russia', 'Maromitsa', '49', null, '6th');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (233, 1, 'Mexico', 'Alvaro Obregon', '4', 'Chiapas', 'Harbort');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (234, 1, 'China', 'Huohua', '20162', null, 'Sachs');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (235, 1, 'Senegal', 'Joal-Fadiout', '67', null, 'Clyde Gallagher');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (236, 1, 'China', 'Jiangyin', '09', null, 'Reindahl');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (237, 1, 'Israel', 'Nahariya', '94342', null, 'Gulseth');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (238, 1, 'Indonesia', 'Ketapang', '3', null, 'Shoshone');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (239, 1, 'Norway', 'Tønsberg', '63069', 'Vestfold', 'Nova');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (240, 1, 'Indonesia', 'Boto', '13774', null, 'Fordem');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (241, 1, 'Kazakhstan', 'Sorang', '6939', null, 'Judy');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (242, 1, 'Argentina', 'San Antonio Oeste', '93371', null, 'Welch');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (243, 1, 'China', 'Longhua', '20', null, 'Jenifer');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (244, 1, 'Pakistan', 'Barishāl', '67203', null, 'Heffernan');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (245, 1, 'China', 'Situ', '9584', null, 'Blackbird');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (246, 1, 'Germany', 'Berlin', '68169', 'Berlin', 'Leroy');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (247, 1, 'Russia', 'Novosmolinskiy', '4398', null, 'Walton');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (248, 1, 'China', 'Batou', '9263', null, 'Mockingbird');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (249, 1, 'Faroe Islands', 'Vestmanna', '57078', null, 'Hoffman');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (250, 1, 'Ireland', 'Whitegate', '822', null, 'Oriole');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (251, 1, 'China', 'Liqiao', '17', null, 'Waxwing');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (252, 1, 'France', 'Laval', '72575', 'Pays de la Loire', 'Union');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (253, 1, 'China', 'Jomda', '9269', null, 'Hintze');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (254, 1, 'Brunei', 'Kuala Belait', '42412', null, 'Cordelia');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (255, 1, 'Philippines', 'Montevista', '6', null, 'Karstens');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (256, 1, 'China', 'Pingyang', '749', null, 'Annamark');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (257, 1, 'Sweden', 'Kalmar', '496', 'Kalmar', 'Nobel');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (258, 1, 'China', 'Dajie', '6901', null, 'Magdeline');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (259, 1, 'Portugal', 'Martinlongo', '30', 'Faro', 'Ilene');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (260, 1, 'Russia', 'Smolensk', '10899', null, 'Karstens');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (261, 1, 'Argentina', 'Caseros', '2', null, 'Laurel');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (262, 1, 'United States', 'Fort Worth', '2', 'Texas', 'Walton');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (263, 1, 'Peru', 'Orurillo', '03', null, 'Granby');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (264, 1, 'Armenia', 'Sarukhan', '05583', null, 'Boyd');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (265, 1, 'Portugal', 'Fontinha', '89694', 'Coimbra', 'Forest');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (266, 1, 'Czech Republic', 'Zborovice', '3', null, 'Londonderry');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (267, 1, 'Czech Republic', 'Králův Dvůr', '6931', null, 'Rigney');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (268, 1, 'China', 'Gaohu', '9', null, 'Carberry');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (269, 1, 'Philippines', 'Antipolo', '8', null, 'Swallow');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (270, 1, 'Argentina', 'Mercedes', '79', null, 'Towne');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (271, 1, 'France', 'Limoges', '5', 'Limousin', 'Delladonna');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (272, 1, 'Thailand', 'Ban Fang', '0260', null, 'Dryden');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (273, 1, 'France', 'Le Havre', '872', 'Haute-Normandie', 'Onsgard');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (274, 1, 'Indonesia', 'Jambeyan', '92', null, 'Helena');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (275, 1, 'Ukraine', 'Oleksandriya', '415', null, 'Burning Wood');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (276, 1, 'Portugal', 'Cimo de Vila', '2', 'Viana do Castelo', 'Mayfield');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (277, 1, 'Czech Republic', 'Litvínov', '400', null, 'Carberry');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (278, 1, 'Japan', 'Katsuura', '3', null, 'Carioca');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (279, 1, 'United States', 'Greensboro', '2', 'North Carolina', 'Springs');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (280, 1, 'Philippines', 'Madrid', '4', null, 'Fair Oaks');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (281, 1, 'Sweden', 'Huddinge', '242', 'Stockholm', 'Glacier Hill');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (282, 1, 'Russia', 'Georgiyevka', '6837', null, 'Farragut');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (283, 1, 'Poland', 'Grębów', '7253', null, 'Grover');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (284, 1, 'Sweden', 'Huskvarna', '49531', 'Jönköping', 'Fulton');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (285, 1, 'Indonesia', 'Pasirsongket Dua', '63664', null, 'Towne');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (286, 1, 'Portugal', 'Alfena', '14711', 'Porto', 'Homewood');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (287, 1, 'Tonga', 'Neiafu', '2171', null, 'Badeau');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (288, 1, 'China', 'Liangdong', '4', null, 'Del Mar');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (289, 1, 'Brazil', 'Batatais', '683', null, 'Meadow Valley');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (290, 1, 'Armenia', 'Hrazdan', '8965', null, 'Corry');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (291, 1, 'Russia', 'Priargunsk', '3521', null, 'Straubel');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (292, 1, 'Bosnia and Herzegovina', 'Pazarić', '6', null, 'Pine View');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (293, 1, 'Indonesia', 'Hegarmanah', '10445', null, 'Riverside');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (294, 1, 'Thailand', 'Uttaradit', '9', null, 'Parkside');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (295, 1, 'Iran', 'Manūjān', '42', null, 'Mifflin');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (296, 1, 'Djibouti', 'Dikhil', '4', null, 'Lawn');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (297, 1, 'China', 'Neikeng', '0676', null, 'Crest Line');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (298, 1, 'Mauritius', 'Camp Ithier', '05394', null, 'Buena Vista');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (299, 1, 'Mexico', 'La Huerta', '34', 'Mexico', 'Glendale');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (300, 1, 'Poland', 'Krzepice', '184', null, 'Golf');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (301, 1, 'Poland', 'Polańczyk', '13', null, 'Rutledge');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (302, 1, 'China', 'Tianhe', '565', null, 'New Castle');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (303, 1, 'Vietnam', 'Bồng Sơn', '09494', null, 'Gateway');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (304, 1, 'Portugal', 'Cobre', '676', 'Lisboa', 'Atwood');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (305, 1, 'Albania', 'Pirg', '6', null, 'Waubesa');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (306, 1, 'Czech Republic', 'Předměřice nad Labem', '81', null, 'Spenser');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (307, 1, 'Sweden', 'Vindeln', '799', 'Västerbotten', 'Lillian');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (308, 1, 'China', 'Pipa', '562', null, 'Knutson');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (309, 1, 'Indonesia', 'Daniwato', '01304', null, 'Elka');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (310, 1, 'Brazil', 'Caculé', '404', null, 'Northwestern');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (311, 1, 'Poland', 'Sypniewo', '61', null, 'Loeprich');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (312, 1, 'Ukraine', 'Semypolky', '4', null, 'Milwaukee');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (313, 1, 'China', 'Zhangjiaji', '034', null, 'Spaight');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (314, 1, 'Turkmenistan', 'Türkmenabat', '85528', null, 'Kim');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (315, 1, 'Japan', 'Hōjō', '02', null, 'Golden Leaf');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (316, 1, 'China', 'Gyigang', '5795', null, 'Loeprich');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (317, 1, 'Canada', 'Saint-Sauveur', '8268', 'Québec', 'North');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (318, 1, 'Iran', 'Akbarābād', '47040', null, 'Lakeland');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (319, 1, 'China', 'Pingshui', '835', null, 'Macpherson');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (320, 1, 'Czech Republic', 'Velké Němčice', '29', null, 'Rutledge');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (321, 1, 'Ukraine', 'Talalayivka', '303', null, 'Holmberg');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (322, 1, 'Comoros', 'Limbi', '61844', null, 'Nobel');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (323, 1, 'Indonesia', 'Panayagan', '28398', null, 'Talisman');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (324, 1, 'Indonesia', 'Wonorejo Dua', '40', null, 'Welch');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (325, 1, 'Bosnia and Herzegovina', 'Dobrljin', '2765', null, 'Anhalt');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (326, 1, 'Russia', 'Pokrovka', '7', null, 'Jackson');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (327, 1, 'Zambia', 'Mufulira', '97005', null, 'Main');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (328, 1, 'Russia', 'Vodnyy', '062', null, 'Raven');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (329, 1, 'Uganda', 'Dokolo', '65619', null, 'Eagan');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (330, 1, 'China', 'Yangzi Jianglu', '9', null, 'Bashford');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (331, 1, 'Philippines', 'Palompon', '907', null, 'Burrows');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (332, 1, 'Portugal', 'Monte Leite', '62707', 'Lisboa', 'Parkside');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (333, 1, 'Indonesia', 'Magersari', '63', null, 'Jackson');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (334, 1, 'Indonesia', 'Carodok', '09427', null, 'Annamark');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (335, 1, 'Nigeria', 'Etinan', '831', null, 'Forster');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (336, 1, 'Mexico', 'Cuauhtemoc', '51', 'Guerrero', 'Loeprich');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (337, 1, 'France', 'Paris 12', '74', 'Île-de-France', 'Main');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (338, 1, 'Ukraine', 'Kobyzhcha', '5155', null, 'Troy');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (339, 1, 'China', 'Nuoxizhi', '2738', null, 'Goodland');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (340, 1, 'China', 'Rifeng', '81', null, 'Golden Leaf');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (341, 1, 'Indonesia', 'Rejoagung', '72387', null, 'Rowland');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (342, 1, 'Indonesia', 'Cerme Kidul', '9125', null, 'New Castle');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (343, 1, 'China', 'Tianhu', '9', null, 'Killdeer');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (344, 1, 'United States', 'Houston', '6815', 'Texas', 'Ilene');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (345, 1, 'Denmark', 'København', '825', 'Region Hovedstaden', 'Duke');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (346, 1, 'Chad', 'Biltine', '7318', null, 'Kinsman');
