insert into address (gid, atype, Country, City, Streetno, brgy, street) values (1, 2, 'Western Sahara', 'Dakhla', '7009', null, 'Del Mar');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (2, 2, 'Thailand', 'Chanthaburi', '21', null, 'Northview');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (3, 2, 'China', 'Beizhouzi', '04425', null, 'Onsgard');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (4, 2, 'Indonesia', 'Banjar Dauhmargi', '81', null, 'Donald');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (5, 2, 'Indonesia', 'Eci', '65744', null, 'Kennedy');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (6, 2, 'Portugal', 'Almendra', '9', 'Guarda', 'Novick');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (7, 2, 'Kazakhstan', 'Ognevka', '87625', null, 'Ridge Oak');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (8, 2, 'Lesotho', 'Leribe', '8041', null, 'Sutteridge');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (9, 2, 'Nicaragua', 'Masachapa', '7271', null, 'Leroy');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (10, 2, 'China', 'Changhe', '357', null, 'Canary');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (11, 2, 'China', 'Dalongdong', '107', null, 'La Follette');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (12, 2, 'Nepal', 'Dhangarhi', '3666', null, 'Burning Wood');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (13, 2, 'Colombia', 'El Retén', '8191', null, 'Blue Bill Park');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (14, 2, 'Indonesia', 'Kepel', '17407', null, 'Roth');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (15, 2, 'Portugal', 'Chãos', '8342', 'Viseu', 'Fisk');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (16, 2, 'Argentina', 'Villa Dolores', '4995', null, 'Twin Pines');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (17, 2, 'Russia', 'Komsomolets', '25414', null, 'Melvin');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (18, 2, 'Morocco', 'Zouiat ech Cheïkh', '58315', null, 'Sachs');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (19, 2, 'Japan', 'Koga', '21765', null, 'Bellgrove');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (20, 2, 'Indonesia', 'Mandala', '673', null, 'Roxbury');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (21, 2, 'Russia', 'Pavlovka', '149', null, 'Menomonie');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (22, 2, 'Indonesia', 'Tlogosari', '64', null, 'Kedzie');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (23, 2, 'Greece', 'Gérakas', '5176', null, 'Division');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (24, 2, 'China', 'Altan Emel', '95', null, '1st');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (25, 2, 'France', 'Limoges', '5', 'Limousin', 'Dahle');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (26, 2, 'Botswana', 'Francistown', '71939', null, 'Jay');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (27, 2, 'Albania', 'Fier', '6749', null, 'Kropf');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (28, 2, 'Russia', 'Palkino', '081', null, 'Manufacturers');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (29, 2, 'Tajikistan', 'Konibodom', '2049', null, 'Mifflin');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (30, 2, 'Poland', 'Dziewin', '0664', null, 'Kipling');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (31, 2, 'China', 'Xinchengpu', '4', null, 'Northview');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (32, 2, 'Indonesia', 'Lembur Tengah', '0903', null, 'Jay');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (33, 2, 'Afghanistan', 'Dū Qal‘ah', '1355', null, 'Ridge Oak');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (34, 2, 'China', 'Guyang', '761', null, 'Nobel');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (35, 2, 'China', 'Xianqiao', '19822', null, 'Lighthouse Bay');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (36, 2, 'China', 'Huacheng', '4690', null, 'Park Meadow');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (37, 2, 'Bangladesh', 'Mehendiganj', '06', null, 'Lakewood Gardens');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (38, 2, 'Peru', 'Acas', '00860', null, 'Truax');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (39, 2, 'Tanzania', 'Mtimbira', '89', null, 'Mariners Cove');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (40, 2, 'Norway', 'Stord', '6', 'Hordaland', 'Westerfield');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (41, 2, 'Portugal', 'Soito', '93802', 'Viseu', 'Service');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (42, 2, 'Thailand', 'Chamni', '2', null, 'Granby');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (43, 2, 'Armenia', 'Tsaghkunk’', '57', null, 'Lillian');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (44, 2, 'Spain', 'Badajoz', '6', 'Extremadura', 'Becker');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (45, 2, 'Bosnia and Herzegovina', 'Velika Kladuša', '72', null, 'Everett');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (46, 2, 'China', 'Luoluopu', '23', null, 'Memorial');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (47, 2, 'Indonesia', 'Jeong', '48088', null, 'Green Ridge');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (48, 2, 'Iran', 'Zarrīn Shahr', '30809', null, 'Warner');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (49, 2, 'Cameroon', 'Garoua', '259', null, 'Fuller');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (50, 2, 'Mexico', 'San Isidro', '85', 'Mexico', 'Ronald Regan');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (51, 2, 'Philippines', 'Baroy', '41', null, 'Debra');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (52, 2, 'France', 'Marseille', '73011', 'Provence-Alpes-Côte d''Azur', 'Twin Pines');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (53, 2, 'China', 'Hongqi', '632', null, 'Veith');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (54, 2, 'Brazil', 'Itaberaí', '2', null, 'Loeprich');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (55, 2, 'China', 'Jiaoxie', '8306', null, 'Michigan');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (56, 2, 'Portugal', 'Devesa', '845', 'Viana do Castelo', 'Eagan');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (57, 2, 'Spain', 'Gijon', '7', 'Asturias', 'Nancy');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (58, 2, 'Portugal', 'Vaiamonte', '1518', 'Portalegre', 'Bartillon');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (59, 2, 'Luxembourg', 'Kopstal', '370', null, 'Menomonie');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (60, 2, 'Afghanistan', 'Jalālābād', '42', null, 'Marquette');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (61, 2, 'China', 'Huaikan', '0', null, 'Briar Crest');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (62, 2, 'Luxembourg', 'Reisdorf', '3', null, 'Florence');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (63, 2, 'Sweden', 'Skinnskatteberg', '89', 'Västmanland', 'Twin Pines');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (64, 2, 'China', 'Xuexi', '74', null, 'Kim');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (65, 2, 'Philippines', 'Guiset East', '569', null, 'Rockefeller');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (66, 2, 'Colombia', 'Cereté', '05', null, 'Meadow Valley');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (67, 2, 'Pakistan', 'Karaundi', '8', null, 'Northfield');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (68, 2, 'Colombia', 'Buenaventura', '36446', null, 'Manufacturers');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (69, 2, 'Indonesia', 'Cikomara', '16574', null, 'Packers');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (70, 2, 'Russia', 'Bezenchuk', '44', null, 'Dixon');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (71, 2, 'Thailand', 'Nong Chik', '04339', null, 'Spaight');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (72, 2, 'China', 'Shuangqiao', '81', null, 'Bayside');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (73, 2, 'France', 'Albi', '2', 'Midi-Pyrénées', 'Sachs');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (74, 2, 'China', 'Xushuguan', '20368', null, 'Hooker');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (75, 2, 'Yemen', 'Radā‘', '6', null, 'Bellgrove');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (76, 2, 'Argentina', 'Clorinda', '4083', null, 'Rusk');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (77, 2, 'Philippines', 'Tarlac City', '32599', null, 'Doe Crossing');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (78, 2, 'United States', 'Amarillo', '324', 'Texas', 'Doe Crossing');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (79, 2, 'Indonesia', 'Trenggulunan', '85259', null, 'Mayer');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (80, 2, 'Brazil', 'Vitória', '9', null, 'Green');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (81, 2, 'Brazil', 'Itarana', '52', null, 'Eastlawn');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (82, 2, 'Bolivia', 'Santiago del Torno', '44', null, 'Sutteridge');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (83, 2, 'China', 'Batou', '8', null, 'Hazelcrest');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (84, 2, 'Philippines', 'Lumbangan', '286', null, 'Barnett');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (85, 2, 'Portugal', 'Gondar', '0', 'Braga', 'Bonner');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (86, 2, 'Czech Republic', 'Plavy', '88527', null, 'Memorial');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (87, 2, 'Thailand', 'Sam Khok', '35266', null, 'Anthes');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (88, 2, 'United Kingdom', 'Bristol', '7683', 'England', 'Fairfield');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (89, 2, 'Ukraine', 'Balaklava', '75', null, 'Sundown');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (90, 2, 'Syria', 'Al Mayādīn', '2', null, 'Clemons');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (91, 2, 'Sierra Leone', 'Lago', '64', null, 'Acker');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (92, 2, 'Thailand', 'Bang Yai', '3529', null, 'Cascade');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (93, 2, 'Russia', 'Novokuz’minki', '5908', null, 'Springview');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (94, 2, 'Portugal', 'Monte Novo', '73', 'Setúbal', 'Sommers');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (95, 2, 'China', 'Jieshou', '26129', null, 'Prairie Rose');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (96, 2, 'Brazil', 'Pindaré Mirim', '7038', null, 'Scofield');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (97, 2, 'Russia', 'Severomorsk', '4692', null, 'Forest Dale');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (98, 2, 'China', 'Jiyukou', '37631', null, 'Rockefeller');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (99, 2, 'Argentina', 'Ceres', '20', null, 'Barnett');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (100, 2, 'United States', 'El Paso', '46', 'Texas', 'Kings');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (101, 2, 'Guam', 'Agat Village', '35250', null, 'Vernon');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (102, 2, 'Slovenia', 'Bakovci', '0', null, 'West');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (103, 2, 'Russia', 'Rudnichnyy', '8', null, 'Stone Corner');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (104, 2, 'Ghana', 'Sekondi-Takoradi', '703', null, 'Eastwood');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (105, 2, 'Ukraine', 'Spas', '1414', null, 'Village Green');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (106, 2, 'Indonesia', 'Cinangka', '931', null, 'Packers');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (107, 2, 'China', 'Huayuan', '64488', null, 'Luster');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (108, 2, 'Brazil', 'Içara', '95651', null, 'Hudson');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (109, 2, 'Indonesia', 'Kapakabisa', '0434', null, 'Merchant');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (110, 2, 'Canada', 'Saint John', '9526', 'New Brunswick', 'Welch');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (111, 2, 'China', 'Andongwei', '354', null, 'Nova');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (112, 2, 'Indonesia', 'Palangan', '58', null, 'Dawn');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (113, 2, 'Kyrgyzstan', 'Cholpon-Ata', '64725', null, 'Sheridan');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (114, 2, 'Egypt', 'Idfu', '5', null, 'Crest Line');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (115, 2, 'Brazil', 'Barueri', '873', null, 'Onsgard');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (116, 2, 'Ukraine', 'Kopychyntsi', '87', null, 'Arizona');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (117, 2, 'Egypt', 'Shibīn al Qanāţir', '90', null, 'Golf View');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (118, 2, 'Colombia', 'San Juan Nepomuceno', '354', null, 'Continental');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (119, 2, 'United States', 'Tulsa', '0', 'Oklahoma', 'Old Shore');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (120, 2, 'China', 'Laoshawan', '627', null, 'Anzinger');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (121, 2, 'Sweden', 'Norrköping', '126', 'Östergötland', 'Meadow Ridge');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (122, 2, 'Greece', 'Neochórion', '7', null, 'Morning');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (123, 2, 'China', 'Shitun', '13', null, 'American Ash');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (124, 2, 'Indonesia', 'Cendagah', '6977', null, 'Banding');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (125, 2, 'China', 'Dongda', '46860', null, 'Pankratz');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (126, 2, 'China', 'Sanchahe', '7', null, '3rd');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (127, 2, 'China', 'Fangxian', '07548', null, 'Anthes');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (128, 2, 'Brazil', 'Ananindeua', '288', null, 'Colorado');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (129, 2, 'Cuba', 'Bolondrón', '66', null, 'Park Meadow');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (130, 2, 'Japan', 'Hamakita', '43', null, 'Dovetail');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (131, 2, 'France', 'Lagny-sur-Marne', '7543', 'Île-de-France', 'Golf Course');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (132, 2, 'Malaysia', 'Kuala Terengganu', '56987', 'Terengganu', 'Morningstar');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (133, 2, 'France', 'Paris 12', '69923', 'Île-de-France', 'Elmside');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (134, 2, 'China', 'Dayingjie', '012', null, 'Express');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (135, 2, 'China', 'Xinzhai', '67926', null, 'Valley Edge');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (136, 2, 'China', 'Heyou', '61400', null, 'Oakridge');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (137, 2, 'Poland', 'Zbąszyń', '50', null, 'Dorton');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (138, 2, 'Ukraine', 'Mahdalynivka', '6', null, 'Jackson');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (139, 2, 'Indonesia', 'Oebobo', '349', null, 'Manley');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (140, 2, 'China', 'Shengrenjian', '51231', null, 'Stuart');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (141, 2, 'China', 'Shenzhengqiao', '1', null, 'Macpherson');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (142, 2, 'Indonesia', 'Tanggeung Kolot', '3923', null, 'Hayes');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (143, 2, 'Colombia', 'Mutatá', '41754', null, 'Superior');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (144, 2, 'Dominican Republic', 'Sabana Iglesia', '47588', null, 'Schiller');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (145, 2, 'China', 'Xambabazar', '7397', null, 'Nobel');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (146, 2, 'Ghana', 'Akim Swedru', '30', null, 'Miller');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (147, 2, 'United States', 'Providence', '947', 'Rhode Island', 'Declaration');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (148, 2, 'Argentina', 'Maipú', '6425', null, 'Pleasure');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (149, 2, 'Mexico', 'Adolfo Ruiz Cortines', '464', 'Veracruz Llave', 'Mallard');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (150, 2, 'Sweden', 'Borås', '46646', 'Västra Götaland', 'Utah');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (151, 2, 'Italy', 'Roma', '282', 'Lazio', 'Becker');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (152, 2, 'Thailand', 'Ban Takhun', '5119', null, 'Susan');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (153, 2, 'Philippines', 'Naagas', '98', null, 'Glendale');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (154, 2, 'Portugal', 'Marteleira', '173', 'Lisboa', 'Hudson');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (155, 2, 'Russia', 'Losino-Petrovskiy', '673', null, 'Kensington');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (156, 2, 'Indonesia', 'Oehaunu', '1387', null, 'Victoria');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (157, 2, 'Cameroon', 'Tcholliré', '52729', null, 'Oxford');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (158, 2, 'China', 'Xinxikou', '598', null, 'Sugar');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (159, 2, 'Portugal', 'Figueiredo', '13', 'Braga', 'Eliot');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (160, 2, 'Russia', 'Uvarovo', '16013', null, 'Valley Edge');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (161, 2, 'Indonesia', 'Pasiraman', '42', null, 'Bartillon');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (162, 2, 'China', 'Xinlong', '9', null, 'Bonner');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (163, 2, 'Japan', 'Kobayashi', '42', null, 'Butterfield');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (164, 2, 'Indonesia', 'Raci Kulon', '11', null, 'Oak');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (165, 2, 'Tanzania', 'Magomeni', '242', null, 'Shopko');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (166, 2, 'Nepal', 'Birendranagar', '66014', null, 'Hovde');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (167, 2, 'Philippines', 'San Vicente', '39525', null, 'Arapahoe');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (168, 2, 'China', 'Baipu', '5', null, 'Magdeline');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (169, 2, 'China', 'Puqian', '365', null, 'Eagan');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (170, 2, 'Greece', 'Gargaliánoi', '092', null, 'Iowa');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (171, 2, 'Brazil', 'Várzea Paulista', '81', null, 'Dorton');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (172, 2, 'South Africa', 'Kriel', '804', null, 'Bunting');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (173, 2, 'Brazil', 'Imbituba', '1', null, 'Morningstar');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (174, 2, 'Belarus', 'Vishow', '98171', null, 'Sloan');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (175, 2, 'Indonesia', 'Margasana', '6749', null, 'Main');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (176, 2, 'Russia', 'Yug', '52647', null, 'Tony');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (177, 2, 'China', 'Huaqiao', '37750', null, 'Russell');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (178, 2, 'Russia', 'Kondinskoye', '40589', null, 'Rutledge');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (179, 2, 'Indonesia', 'Tlogowungu', '40', null, 'Roth');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (180, 2, 'Yemen', 'Ad Dīs ash Sharqīyah', '3912', null, 'Delaware');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (181, 2, 'Belarus', 'Shchuchin', '898', null, 'Warrior');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (182, 2, 'China', 'Zhoujiadian', '22', null, 'Lerdahl');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (183, 2, 'Indonesia', 'Sidonganti', '4', null, 'Fuller');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (184, 2, 'Indonesia', 'Salamnunggal', '1134', null, 'Elka');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (185, 2, 'Portugal', 'Urrô', '8', 'Porto', 'Walton');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (186, 2, 'Indonesia', 'Langkaplancar', '913', null, 'Corscot');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (187, 2, 'China', 'Helong', '2', null, 'Blaine');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (188, 2, 'Peru', 'Lloque', '1565', null, 'Spenser');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (189, 2, 'Finland', 'Kuhmo', '50865', null, 'Stuart');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (190, 2, 'France', 'Suresnes', '96', 'Île-de-France', 'Lakewood');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (191, 2, 'Bosnia and Herzegovina', 'Gornje Moštre', '69987', null, 'International');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (192, 2, 'China', 'Moyuan', '684', null, 'Amoth');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (193, 2, 'Russia', 'Tuymazy', '0941', null, 'Stuart');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (194, 2, 'Slovenia', 'Kisovec', '9', null, 'Comanche');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (195, 2, 'South Sudan', 'Raga', '0', null, 'Cody');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (196, 2, 'France', 'Privas', '226', 'Rhône-Alpes', 'Nobel');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (197, 2, 'Poland', 'Raszczyce', '25', null, 'Laurel');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (198, 2, 'China', 'Jielong', '777', null, 'Center');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (199, 2, 'Brazil', 'Cruzília', '348', null, 'Duke');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (200, 2, 'China', 'Ezhou', '94', null, 'Bartelt');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (201, 2, 'Sweden', 'Skärhamn', '4', 'Västra Götaland', 'Mallory');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (202, 2, 'China', 'Wenping', '0', null, 'Trailsway');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (203, 2, 'Indonesia', 'Wolofeo', '7', null, 'Hallows');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (204, 2, 'Guatemala', 'San Lorenzo', '2307', null, 'Wayridge');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (205, 2, 'Russia', 'Nevel’', '91022', null, 'Pankratz');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (206, 2, 'Philippines', 'Boljoon', '0', null, 'Havey');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (207, 2, 'Panama', 'Veracruz', '0', null, 'Haas');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (208, 2, 'Peru', 'Yuracyacu', '76', null, 'Bunting');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (209, 2, 'Indonesia', 'Kota Trieng', '173', null, 'David');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (210, 2, 'China', 'Shuikou', '49', null, 'Artisan');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (211, 2, 'Sweden', 'Helsingborg', '8518', 'Skåne', 'Raven');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (212, 2, 'Serbia', 'Bački Breg', '352', null, 'Grasskamp');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (213, 2, 'China', 'Honglin', '9', null, 'Homewood');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (214, 2, 'Yemen', 'Ar Rubū‘', '58', null, 'Spenser');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (215, 2, 'Indonesia', 'Kutacane', '2233', null, 'Florence');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (216, 2, 'China', 'Lezhu', '4', null, '3rd');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (217, 2, 'Belarus', 'Kastsyukowka', '312', null, 'Dorton');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (218, 2, 'Poland', 'Garbów', '5', null, 'Burning Wood');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (219, 2, 'Indonesia', 'Krajan Dua Patempuran', '2115', null, 'Fallview');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (220, 2, 'Australia', 'Brisbane', '3655', 'Queensland', 'Paget');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (221, 2, 'China', 'Mingjiu', '794', null, 'Hanover');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (222, 2, 'Ukraine', 'Chornomors’ke', '8', null, '6th');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (223, 2, 'China', 'Haixing', '2127', null, 'Sunbrook');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (224, 2, 'Poland', 'Stanisław Górny', '31915', null, 'Oak Valley');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (225, 2, 'Ukraine', 'Berehomet', '1259', null, 'Oak');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (226, 2, 'China', 'Hushi', '895', null, 'Granby');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (227, 2, 'Indonesia', 'Jabon', '437', null, 'Clarendon');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (228, 2, 'Philippines', 'Carig', '55', null, 'Vermont');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (229, 2, 'Zambia', 'Kataba', '44', null, 'Hanover');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (230, 2, 'Czech Republic', 'Havířov', '5', null, 'Sutteridge');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (231, 2, 'Egypt', '‘Izbat al Burj', '397', null, 'Alpine');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (232, 2, 'China', 'Cuozheqiangma', '9707', null, 'Holmberg');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (233, 2, 'Hungary', 'Miskolc', '22', 'Borsod-Abaúj-Zemplén', 'Evergreen');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (234, 2, 'Belarus', 'Ivyanyets', '10', null, 'Mcguire');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (235, 2, 'Morocco', 'Tizgane', '6', null, 'Burning Wood');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (236, 2, 'Argentina', 'Jacinto Arauz', '3908', null, 'Graceland');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (237, 2, 'Poland', 'Dąbrowa', '97', null, 'Florence');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (238, 2, 'Czech Republic', 'Ropice', '94', null, 'Sage');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (239, 2, 'Iraq', 'Balad', '2194', null, 'Dixon');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (240, 2, 'France', 'Saint-Lô', '9617', 'Basse-Normandie', 'Nancy');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (241, 2, 'China', 'Dayou', '00', null, 'Novick');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (242, 2, 'Uzbekistan', 'Komsomol’skiy', '81417', null, 'Algoma');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (243, 2, 'France', 'Paris 13', '834', 'Île-de-France', 'Sage');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (244, 2, 'Japan', 'Kawaguchi', '2854', null, 'Blaine');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (245, 2, 'Cameroon', 'Douala', '266', null, 'Towne');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (246, 2, 'Netherlands', 'Doetinchem', '158', 'Provincie Gelderland', 'Sherman');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (247, 2, 'Zambia', 'Chambishi', '0380', null, 'Old Gate');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (248, 2, 'Philippines', 'Bigaa', '88498', null, 'Bowman');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (249, 2, 'Indonesia', 'Ngundaan', '69', null, 'Iowa');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (250, 2, 'Argentina', 'Gaimán', '2', null, 'Spaight');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (251, 2, 'China', 'Yushugou', '11941', null, 'Declaration');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (252, 2, 'China', 'Xin’an', '0', null, '2nd');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (253, 2, 'Japan', 'Ōdate', '925', null, 'Waywood');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (254, 2, 'China', 'Muqi', '98654', null, 'Scott');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (255, 2, 'Ukraine', 'Roskoshnyy', '6', null, 'Florence');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (256, 2, 'Palestinian Territory', 'Bīr Zayt', '93', null, 'Fuller');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (257, 2, 'China', 'Magang', '37954', null, 'Moland');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (258, 2, 'Russia', 'Ostankinskiy', '08', null, 'Burrows');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (259, 2, 'Finland', 'Tuusniemi', '76374', null, 'Village');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (260, 2, 'Lithuania', 'Žiežmariai', '9', null, 'Scoville');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (261, 2, 'El Salvador', 'Intipucá', '697', null, 'Veith');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (262, 2, 'Norway', 'Drammen', '588', 'Buskerud', 'Jackson');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (263, 2, 'Japan', 'Atami', '92157', null, 'Mcbride');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (264, 2, 'Bosnia and Herzegovina', 'Jajce', '09612', null, 'Troy');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (265, 2, 'Libya', 'Al ‘Azīzīyah', '84439', null, 'Sutherland');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (266, 2, 'Albania', 'Lukovë', '5900', null, 'Heath');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (267, 2, 'Poland', 'Skrzydlna', '49', null, 'Anderson');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (268, 2, 'Zimbabwe', 'Gweru', '39650', null, 'Bultman');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (269, 2, 'Argentina', 'Dalmacio Vélez Sársfield', '8636', null, 'Gateway');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (270, 2, 'Indonesia', 'Kondangrege', '3', null, 'Debs');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (271, 2, 'Thailand', 'Na Kae', '606', null, 'Twin Pines');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (272, 2, 'Indonesia', 'Baroh', '5387', null, 'Fieldstone');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (273, 2, 'Philippines', 'La Paz', '2213', null, 'Rutledge');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (274, 2, 'Japan', 'Izumiōtsu', '28', null, 'Colorado');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (275, 2, 'China', 'Oymak', '4', null, 'Cambridge');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (276, 2, 'Afghanistan', 'Deh-e Now', '59715', null, 'Rowland');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (277, 2, 'Spain', 'Aviles', '4', 'Asturias', 'Ramsey');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (278, 2, 'Ecuador', 'Baños', '4987', null, 'Troy');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (279, 2, 'Indonesia', 'Bader', '1', null, 'Burrows');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (280, 2, 'China', 'Huayuan', '2', null, 'Moose');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (281, 2, 'Cuba', 'Nueva Gerona', '64', null, 'Blue Bill Park');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (282, 2, 'China', 'Raofeng', '9842', null, 'Bartillon');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (283, 2, 'Japan', 'Toyoshina', '00', null, 'Columbus');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (284, 2, 'El Salvador', 'El Congo', '70', null, 'Duke');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (285, 2, 'China', 'Weixin', '0', null, 'Center');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (286, 2, 'Morocco', 'Casablanca', '60', null, 'Elgar');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (287, 2, 'Russia', 'Perovo', '5732', null, 'Clarendon');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (288, 2, 'China', 'Wanmingang', '75919', null, 'Crest Line');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (289, 2, 'Japan', 'Dazaifu', '9', null, 'Delladonna');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (290, 2, 'United States', 'Tallahassee', '6619', 'Florida', 'Rigney');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (291, 2, 'Poland', 'Korczew', '58547', null, 'Brown');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (292, 2, 'China', 'Wanbu', '3', null, 'Hansons');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (293, 2, 'Sierra Leone', 'Binkolo', '108', null, 'Fremont');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (294, 2, 'Vietnam', 'Tuy Phước', '08', null, 'Debs');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (295, 2, 'Russia', 'Uzlovaya', '32585', null, 'South');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (296, 2, 'Azerbaijan', 'Fizuli', '379', null, 'Toban');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (297, 2, 'Portugal', 'Arão', '31', 'Viana do Castelo', 'Leroy');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (298, 2, 'Philippines', 'Lawa-an', '817', null, 'Utah');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (299, 2, 'South Africa', 'Modimolle', '185', null, 'Westerfield');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (300, 2, 'Philippines', 'San Basilio', '45', null, 'Lakewood Gardens');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (301, 2, 'Colombia', 'Guachucal', '324', null, 'Lindbergh');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (302, 2, 'South Sudan', 'Raga', '9', null, 'Weeping Birch');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (303, 2, 'Saudi Arabia', 'Al Majāridah', '04', null, 'Cody');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (304, 2, 'Cameroon', 'Douala', '93', null, 'Blackbird');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (305, 2, 'Brazil', 'Concórdia', '1839', null, 'Division');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (306, 2, 'Mexico', 'Santa Cruz', '54', 'Oaxaca', 'Loomis');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (307, 2, 'Croatia', 'Ivanec', '47', null, 'Thompson');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (308, 2, 'Thailand', 'Wat Sing', '12065', null, 'Weeping Birch');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (309, 2, 'Peru', 'Succha', '55496', null, 'Manufacturers');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (310, 2, 'Norway', 'Oslo', '35469', 'Oslo', 'Monica');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (311, 2, 'Guatemala', 'Colotenango', '62', null, 'Scott');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (312, 2, 'Colombia', 'Saboyá', '40', null, 'Eagle Crest');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (313, 2, 'Indonesia', 'Cigeulis', '30423', null, 'Division');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (314, 2, 'China', 'Dawang', '4', null, 'Maywood');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (315, 2, 'Vietnam', 'Thị Trấn Quán Lào', '215', null, 'Roxbury');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (316, 2, 'Brazil', 'Ibaté', '14', null, 'Kedzie');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (317, 2, 'China', 'Liufu', '40613', null, 'Butternut');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (318, 2, 'Jordan', 'As Salţ', '945', null, 'Blaine');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (319, 2, 'United Kingdom', 'Walton', '64631', 'England', 'Fallview');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (320, 2, 'Poland', 'Tomaszów Mazowiecki', '606', null, 'Valley Edge');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (321, 2, 'Nigeria', 'Kamba', '67', null, 'Gulseth');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (322, 2, 'Honduras', 'Liure', '1065', null, 'Maywood');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (323, 2, 'Indonesia', 'Wurigelebur', '84', null, 'Bunting');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (324, 2, 'South Korea', 'Gwangtan', '4', null, 'Dryden');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (325, 2, 'Russia', 'Kuybyshevskiy Zaton', '40664', null, 'Spenser');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (326, 2, 'France', 'Lunel', '6785', 'Languedoc-Roussillon', 'Bartillon');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (327, 2, 'Dominican Republic', 'Hato Mayor del Rey', '89', null, 'Loomis');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (328, 2, 'Philippines', 'Isla', '66', null, 'Macpherson');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (329, 2, 'Peru', 'Catache', '17', null, 'La Follette');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (330, 2, 'Taiwan', 'Daxi', '00', null, 'Morningstar');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (331, 2, 'Indonesia', 'Fatumuti', '6939', null, 'Dorton');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (332, 2, 'Sweden', 'Stockholm', '11', 'Stockholm', 'Main');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (333, 2, 'Philippines', 'Bagumbayan', '78152', null, 'Prentice');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (334, 2, 'China', 'Sanjian', '27986', null, 'Ilene');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (335, 2, 'Somalia', 'Bosaso', '10', null, 'Kedzie');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (336, 2, 'Russia', 'Pogranichnyy', '6', null, 'Maple Wood');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (337, 2, 'Philippines', 'Bayog', '925', null, 'Calypso');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (338, 2, 'China', 'Yong’an', '7702', null, 'Ronald Regan');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (339, 2, 'Indonesia', 'Tarogong', '817', null, 'Everett');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (340, 2, 'Ukraine', 'Vary', '16813', null, 'Moulton');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (341, 2, 'Ukraine', 'Sartana', '040', null, 'Ludington');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (342, 2, 'Venezuela', 'Cúa', '5', null, 'Southridge');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (343, 2, 'Croatia', 'Ljupina', '6', null, 'Saint Paul');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (344, 2, 'Indonesia', 'Jambangan', '2', null, 'Glacier Hill');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (345, 2, 'Canada', 'Ponoka', '60698', 'Alberta', 'Truax');
insert into address (gid, atype, Country, City, Streetno, brgy, street) values (346, 2, 'United Kingdom', 'Seaton', '635', 'England', 'Upham');
