-- MySQL Script generated by MySQL Workbench
-- Tue Aug 15 13:55:17 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema msadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema msadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `msadb` DEFAULT CHARACTER SET latin1 ;
USE `msadb` ;

-- -----------------------------------------------------
-- Table `msadb`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msadb`.`account` (
  `accid` INT(11) NOT NULL AUTO_INCREMENT,
  `uname` VARCHAR(45) NULL DEFAULT NULL,
  `hash` VARCHAR(60) NULL DEFAULT NULL,
  `type` INT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`accid`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `msadb`.`guards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msadb`.`guards` (
  `GID` INT(11) NOT NULL AUTO_INCREMENT,
  `FN` VARCHAR(45) NULL DEFAULT NULL,
  `MN` VARCHAR(45) NULL DEFAULT NULL,
  `LN` VARCHAR(45) NULL DEFAULT NULL,
  `GStatus` INT(11) NULL DEFAULT NULL,
  `BDate` VARCHAR(45) NULL DEFAULT NULL,
  `Gender` INT(11) NULL DEFAULT NULL,
  `Height` VARCHAR(45) NULL DEFAULT NULL,
  `Weight` VARCHAR(45) NULL DEFAULT NULL,
  `Religion` VARCHAR(45) NULL DEFAULT NULL,
  `CivilStatus` INT(11) NULL DEFAULT NULL,
  `CellNo` VARCHAR(45) NULL DEFAULT NULL,
  `TelNo` VARCHAR(45) NULL DEFAULT NULL,
  `LicenseNo` VARCHAR(45) NULL DEFAULT NULL,
  `SSS` VARCHAR(45) NULL DEFAULT NULL,
  `TIN` VARCHAR(45) NULL DEFAULT NULL,
  `PhilHealth` VARCHAR(45) NULL DEFAULT NULL,
  `PrevAgency` VARCHAR(45) NULL DEFAULT NULL,
  `PrevAss` VARCHAR(200) NULL DEFAULT NULL,
  `EdAtt` INT(11) NULL DEFAULT NULL,
  `Course` VARCHAR(45) NULL DEFAULT NULL,
  `MilitaryTrainings` VARCHAR(200) NULL DEFAULT NULL,
  `EmergencyContact` VARCHAR(45) NULL DEFAULT NULL,
  `EmergencyNo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`GID`))
ENGINE = InnoDB
AUTO_INCREMENT = 347
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `msadb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msadb`.`address` (
  `AID` INT(11) NOT NULL AUTO_INCREMENT,
  `GID` INT(11) NULL DEFAULT NULL,
  `AType` INT(11) NULL DEFAULT NULL,
  `Country` VARCHAR(45) NULL DEFAULT NULL,
  `City` VARCHAR(45) NULL DEFAULT NULL,
  `StreetNo` VARCHAR(45) NULL DEFAULT NULL,
  `Brgy` VARCHAR(45) NULL DEFAULT NULL,
  `Street` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`AID`),
  CONSTRAINT `Guard-Add`
    FOREIGN KEY (`GID`)
    REFERENCES `msadb`.`guards` (`GID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `Guard-Add_idx` ON `msadb`.`address` (`GID` ASC);


-- -----------------------------------------------------
-- Table `msadb`.`adjustment_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msadb`.`adjustment_log` (
  `AdjID` INT(11) NOT NULL AUTO_INCREMENT,
  `PID` INT(11) NULL DEFAULT NULL,
  `AdjType` INT(11) NULL DEFAULT NULL,
  `AdjDate` TIMESTAMP NULL DEFAULT NULL,
  `Value` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`AdjID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `Adj-Payroll_idx` ON `msadb`.`adjustment_log` (`PID` ASC);


-- -----------------------------------------------------
-- Table `msadb`.`payroll`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msadb`.`payroll` (
  `PID` INT(11) NOT NULL AUTO_INCREMENT,
  `GID` INT(11) NULL DEFAULT NULL,
  `month` INT(2) NULL DEFAULT NULL,
  `period` INT(2) NULL DEFAULT NULL,
  `year` INT(4) NULL DEFAULT NULL,
  `rates_id` INT(11) NULL DEFAULT NULL,
  `cashbond` DECIMAL(7,2) NULL DEFAULT NULL,
  `thirteenth` DECIMAL(7,2) NULL DEFAULT NULL,
  `cola` DECIMAL(7,2) NULL DEFAULT NULL,
  `sss` DECIMAL(7,2) NULL DEFAULT NULL,
  `pagibig` DECIMAL(7,2) NULL DEFAULT NULL,
  `philhealth` DECIMAL(7,2) NULL DEFAULT NULL,
  `withtax` DECIMAL(7,2) NULL DEFAULT NULL,
  `cashadv` DECIMAL(7,2) NULL DEFAULT '0.00',
  `emergencyallowance` DECIMAL(7,2) NULL DEFAULT NULL,
  `totalsummary_serializable` BLOB NULL DEFAULT NULL,
  `hc_serializable` BLOB NULL DEFAULT NULL,
  `lastmodified` TIMESTAMP NULL DEFAULT NULL,
  `pstatus` INT(1) NULL DEFAULT NULL,
  `basicpayhourly` DECIMAL(7,2) NULL DEFAULT NULL,
  PRIMARY KEY (`PID`),
  CONSTRAINT `Payroll-Guards`
    FOREIGN KEY (`GID`)
    REFERENCES `msadb`.`guards` (`GID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `py_unq_idx` ON `msadb`.`payroll` (`GID` ASC, `year` ASC, `month` ASC, `period` ASC);

CREATE INDEX `Payroll-Guards_idx` ON `msadb`.`payroll` (`GID` ASC);


-- -----------------------------------------------------
-- Table `msadb`.`adjustments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msadb`.`adjustments` (
  `AdjID` INT(11) NOT NULL AUTO_INCREMENT,
  `PID` INT(11) NULL DEFAULT NULL,
  `AdjType` INT(11) NULL DEFAULT NULL,
  `AdjDate` VARCHAR(45) NULL DEFAULT NULL,
  `Value` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`AdjID`),
  CONSTRAINT `Adj-Payroll`
    FOREIGN KEY (`PID`)
    REFERENCES `msadb`.`payroll` (`PID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `Adj-Payroll_idx` ON `msadb`.`adjustments` (`PID` ASC);


-- -----------------------------------------------------
-- Table `msadb`.`sduty_assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msadb`.`sduty_assignment` (
  `AID` INT(11) NOT NULL AUTO_INCREMENT,
  `GID` INT(11) NULL DEFAULT NULL,
  `RAID` INT(11) NULL DEFAULT NULL,
  `AStatus` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`AID`),
  CONSTRAINT `Assignment-Guard`
    FOREIGN KEY (`GID`)
    REFERENCES `msadb`.`guards` (`GID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `Assignment-Guard_idx` ON `msadb`.`sduty_assignment` (`GID` ASC);

CREATE INDEX `Assignment-Request_idx` ON `msadb`.`sduty_assignment` (`RAID` ASC);


-- -----------------------------------------------------
-- Table `msadb`.`dutydetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msadb`.`dutydetails` (
  `DID` INT(11) NOT NULL AUTO_INCREMENT,
  `AID` INT(11) NULL DEFAULT NULL,
  `TI_hh` INT(2) UNSIGNED ZEROFILL NULL DEFAULT NULL,
  `TI_mm` INT(2) UNSIGNED ZEROFILL NULL DEFAULT NULL,
  `TI_period` VARCHAR(3) NULL DEFAULT NULL,
  `TO_hh` INT(2) UNSIGNED ZEROFILL NULL DEFAULT NULL,
  `TO_mm` INT(2) UNSIGNED ZEROFILL NULL DEFAULT NULL,
  `TO_period` VARCHAR(3) NULL DEFAULT NULL,
  `Mon` INT(1) UNSIGNED NULL DEFAULT NULL,
  `Tue` INT(1) UNSIGNED NULL DEFAULT NULL,
  `Wed` INT(1) UNSIGNED NULL DEFAULT NULL,
  `Thu` INT(1) UNSIGNED NULL DEFAULT NULL,
  `Fri` INT(1) UNSIGNED NULL DEFAULT NULL,
  `Sat` INT(1) UNSIGNED NULL DEFAULT NULL,
  `Sun` INT(1) UNSIGNED NULL DEFAULT NULL,
  `DStatus` INT(1) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`DID`),
  CONSTRAINT `Assignment-Duty`
    FOREIGN KEY (`AID`)
    REFERENCES `msadb`.`sduty_assignment` (`AID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 48
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `Assignment-Duty_idx` ON `msadb`.`dutydetails` (`AID` ASC);


-- -----------------------------------------------------
-- Table `msadb`.`attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msadb`.`attendance` (
  `AtID` INT(11) NOT NULL AUTO_INCREMENT,
  `DID` INT(11) NULL DEFAULT NULL,
  `PID` INT(11) NULL DEFAULT NULL,
  `Date` VARCHAR(45) NULL DEFAULT NULL,
  `TimeIn` VARCHAR(45) NULL DEFAULT '12:00 AM',
  `TimeOut` VARCHAR(45) NULL DEFAULT '12:00 AM',
  PRIMARY KEY (`AtID`),
  CONSTRAINT `Attendance-DutyDetails`
    FOREIGN KEY (`DID`)
    REFERENCES `msadb`.`dutydetails` (`DID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 76
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `unique_index` ON `msadb`.`attendance` (`Date` ASC, `DID` ASC);

CREATE INDEX `Attendance-DutyDetails_idx` ON `msadb`.`attendance` (`DID` ASC);


-- -----------------------------------------------------
-- Table `msadb`.`basicpay`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msadb`.`basicpay` (
  `BPID` INT(11) NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(6,2) NULL DEFAULT NULL,
  `start` DATETIME NULL DEFAULT NULL,
  `end` DATETIME NULL DEFAULT NULL,
  `status` INT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`BPID`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `msadb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msadb`.`client` (
  `CID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `ClientStreetNo` VARCHAR(45) NULL DEFAULT NULL,
  `ClientStreet` VARCHAR(45) NULL DEFAULT NULL,
  `ClientBrgy` VARCHAR(45) NULL DEFAULT NULL,
  `ClientCity` VARCHAR(45) NULL DEFAULT NULL,
  `ContactPerson` VARCHAR(45) NULL DEFAULT NULL,
  `ContactNo` VARCHAR(45) NULL DEFAULT NULL,
  `Manager` VARCHAR(45) NULL DEFAULT NULL,
  `CStatus` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`CID`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `msadb`.`contribdetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msadb`.`contribdetails` (
  `contrib_id` INT(11) NOT NULL AUTO_INCREMENT,
  `date_effective` DATETIME NOT NULL,
  `date_dissolved` DATETIME NULL DEFAULT NULL,
  `type` INT(1) NULL DEFAULT NULL,
  `status` INT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`contrib_id`, `date_effective`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `msadb`.`dependents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msadb`.`dependents` (
  `DeID` INT(11) NOT NULL AUTO_INCREMENT,
  `DRelationship` INT(11) NULL DEFAULT NULL,
  `FN` VARCHAR(45) NULL DEFAULT NULL,
  `MN` VARCHAR(45) NULL DEFAULT NULL,
  `LN` VARCHAR(45) NULL DEFAULT NULL,
  `GID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`DeID`),
  CONSTRAINT `Guards-Dep`
    FOREIGN KEY (`GID`)
    REFERENCES `msadb`.`guards` (`GID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1587
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `Guards-Dep_idx` ON `msadb`.`dependents` (`GID` ASC);


-- -----------------------------------------------------
-- Table `msadb`.`event_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msadb`.`event_log` (
  `evid` INT(11) NOT NULL AUTO_INCREMENT,
  `datefire` DATETIME NULL DEFAULT NULL,
  `type` INT(11) NULL DEFAULT NULL,
  `auto_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`evid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `msadb`.`holiday`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msadb`.`holiday` (
  `hid` INT(11) NOT NULL AUTO_INCREMENT,
  `datestart` VARCHAR(45) NULL DEFAULT NULL,
  `dateend` VARCHAR(45) NULL DEFAULT NULL,
  `type` INT(1) NULL DEFAULT NULL,
  `ds_MM` INT(2) NULL DEFAULT NULL,
  `ds_dd` INT(2) NULL DEFAULT NULL,
  `ds_yyyy` INT(4) NULL DEFAULT NULL,
  `de_MM` INT(2) NULL DEFAULT NULL,
  `de_dd` INT(2) NULL DEFAULT NULL,
  `de_yyyy` INT(4) NULL DEFAULT NULL,
  `desc` VARCHAR(120) NULL DEFAULT NULL,
  `status` INT(1) NULL DEFAULT '1',
  PRIMARY KEY (`hid`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `msadb`.`incidentreport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msadb`.`incidentreport` (
  `IID` INT(11) NOT NULL AUTO_INCREMENT,
  `ReportType` INT(11) NULL DEFAULT NULL,
  `PCompleting` VARCHAR(45) NULL DEFAULT NULL,
  `EventDate` VARCHAR(45) NULL DEFAULT NULL,
  `EventLocation` VARCHAR(45) NULL DEFAULT NULL,
  `Description` LONGTEXT NULL DEFAULT NULL,
  `DateEntry` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`IID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `msadb`.`loginhistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msadb`.`loginhistory` (
  `lid` INT(11) NOT NULL AUTO_INCREMENT,
  `uid` INT(11) NULL DEFAULT NULL,
  `logintime` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`lid`))
ENGINE = InnoDB
AUTO_INCREMENT = 110
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `msadb`.`meta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msadb`.`meta` (
  `meta_id` INT(11) NOT NULL,
  `version` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`meta_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `msadb`.`period`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msadb`.`period` (
  `PID` INT(11) NOT NULL AUTO_INCREMENT,
  `GID` INT(11) NULL DEFAULT NULL,
  `month` INT(2) UNSIGNED ZEROFILL NULL DEFAULT NULL,
  `period` INT(1) UNSIGNED ZEROFILL NULL DEFAULT NULL,
  `year` INT(4) UNSIGNED ZEROFILL NULL DEFAULT NULL,
  `certby` VARCHAR(120) NULL DEFAULT '',
  PRIMARY KEY (`PID`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `unq` ON `msadb`.`period` (`month` ASC, `GID` ASC, `period` ASC, `year` ASC);


-- -----------------------------------------------------
-- Table `msadb`.`personsinvolved`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msadb`.`personsinvolved` (
  `PIID` INT(11) NOT NULL AUTO_INCREMENT,
  `IID` INT(11) NULL DEFAULT NULL,
  `InvolvementType` INT(11) NULL DEFAULT NULL,
  `FN` VARCHAR(45) NULL DEFAULT NULL,
  `MN` VARCHAR(45) NULL DEFAULT NULL,
  `LN` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`PIID`),
  CONSTRAINT `Involved-Report`
    FOREIGN KEY (`IID`)
    REFERENCES `msadb`.`incidentreport` (`IID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `Involved-Report_idx` ON `msadb`.`personsinvolved` (`IID` ASC);


-- -----------------------------------------------------
-- Table `msadb`.`rates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msadb`.`rates` (
  `rates_id` INT(11) NOT NULL AUTO_INCREMENT,
  `date_effective` DATETIME NULL DEFAULT NULL,
  `date_dissolved` DATETIME NULL DEFAULT NULL,
  `contrib_id` INT(11) NULL DEFAULT NULL,
  `ordinary_day` DECIMAL(3,2) NULL DEFAULT NULL,
  `special_holiday` DECIMAL(3,2) NULL DEFAULT NULL,
  `regular_holiday` DECIMAL(3,2) NULL DEFAULT NULL,
  `sunday_ordinary_day` DECIMAL(3,2) NULL DEFAULT NULL,
  `sunday_special_holiday` DECIMAL(3,2) NULL DEFAULT NULL,
  `sunday_regular_holiday` DECIMAL(3,2) NULL DEFAULT NULL,
  `nightdifferential` DECIMAL(3,2) NULL DEFAULT NULL,
  `overtime` DECIMAL(3,2) NULL DEFAULT NULL,
  `overtime_holiday` DECIMAL(3,2) NULL DEFAULT NULL,
  `status` INT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`rates_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `msadb`.`request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msadb`.`request` (
  `RID` INT(11) NOT NULL AUTO_INCREMENT,
  `RequestType` INT(11) NULL DEFAULT NULL,
  `CID` INT(11) NULL DEFAULT NULL,
  `DateEntry` VARCHAR(45) NULL DEFAULT NULL,
  `RStatus` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`RID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `msadb`.`request_assign`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msadb`.`request_assign` (
  `RAID` INT(11) NOT NULL AUTO_INCREMENT,
  `RID` INT(11) NULL DEFAULT NULL,
  `ContractStart` DATETIME NULL DEFAULT NULL,
  `ContractEnd` DATETIME NULL DEFAULT NULL,
  `streetno` VARCHAR(11) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `streetname` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `brgy` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `city` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `NoGuards` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`RAID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `msadb`.`request_dismiss`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msadb`.`request_dismiss` (
  `RDID` INT(11) NOT NULL AUTO_INCREMENT,
  `RID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`RDID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `msadb`.`request_unassign`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msadb`.`request_unassign` (
  `RDID` INT(11) NOT NULL AUTO_INCREMENT,
  `RID` INT(11) NULL DEFAULT NULL,
  `GID` INT(11) NULL DEFAULT NULL,
  `IID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`RDID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `msadb`.`sduty_dismissal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msadb`.`sduty_dismissal` (
  `DisID` INT(11) NOT NULL AUTO_INCREMENT,
  `DID` INT(11) NULL DEFAULT NULL,
  `RDID` INT(11) NULL DEFAULT NULL,
  `DisStatus` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`DisID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `msadb`.`ssscontrib`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msadb`.`ssscontrib` (
  `sssid` INT(11) NOT NULL AUTO_INCREMENT,
  `range_start` DECIMAL(7,2) NULL DEFAULT NULL,
  `range_end` DECIMAL(7,2) NULL DEFAULT NULL,
  `ec` DECIMAL(7,2) NULL DEFAULT NULL,
  `contrib_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`sssid`))
ENGINE = InnoDB
AUTO_INCREMENT = 194
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `msadb`.`withtax_bracket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msadb`.`withtax_bracket` (
  `wbid` INT(11) NOT NULL AUTO_INCREMENT,
  `estatus` VARCHAR(5) NULL DEFAULT NULL,
  `bracket` DECIMAL(7,2) NULL DEFAULT '0.00',
  `bracket_end` DECIMAL(7,2) NULL DEFAULT '0.00',
  `taxid` VARCHAR(45) NULL DEFAULT NULL,
  `contrib_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`wbid`))
ENGINE = InnoDB
AUTO_INCREMENT = 97
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `msadb`.`withtax_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msadb`.`withtax_value` (
  `wid` INT(11) NOT NULL AUTO_INCREMENT,
  `value` DECIMAL(7,2) NULL DEFAULT NULL,
  `excessmult` INT(2) NULL DEFAULT NULL,
  `INT` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`wid`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
